apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJiVVZ6YzJsaFNHOW1SR0Z5U3pwbmFIQmZlREZ3TmpSdE5rRlRiMFZ1UmxsbGRteHpSREpwVm5wSlVWQTVPV2h5TVVOcE0yTjUiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
